config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'products#index'

  
  resources :reservations do
    member do
      put :cancel
    end
  end
  
  resources :products, only: [:index, :show] do
    collection do
      get 'c/:category_id', to: 'products#index', as: :categoried
    end
  end

  authenticate :user, lambda {|user| user.admin? } do
    get '/admin' => 'admin#index'
    get '/recent-reservations' => "pages#recent_reservations", path: '/admin/recent_reservations'
    get '/recent-visits' => "pages#recent_visits", path: '/admin/recent_visits'
    resources :broadcast_messages, only: [:create, :destroy], path: '/admin/broadcast_messages'


    mount PgHero::Engine, at: "pghero"
    mount RailsAdmin::Engine => '/admin/rails_admin', as: 'rails_admin'
  end

end

app/views/pages/recent_reservations.html.erb
<div class="container">

<table class="table">
  <thead>
    <tr>
      <th>Starts at</th>
      <th>User</th>
      <th>Product</th>
      <th>With</th>
      <th>Price</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @recent_reservations.each do |reservation| %>
      <tr class=<%= 'danger' if reservation.is_canceled? %>>
        <td><%= reservation.available_at.strftime("%B %e, %H:%M") %></td>
        <td><%= reservation.user.fullname %></td>
        <td><%= reservation.product.name %></td>
        <td><%= reservation.product.employee %></td>
        <td><%= reservation.product.price %></td>
        <% unless reservation.is_canceled? %>
        <td><%= link_to 'Cancel', cancel_reservation_path(reservation), method: :put %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/pages/recent_visits.html.erb
<div class="container">

<%= form_tag recent_visits_path, method: 'get', html: {role: "form"} do %>
  <p>
  <div class="col-md-6">
    <%= text_field_tag :search, params[:search], placeholder: "Find a visit...", class: "form-control" %>
  </div>
    <%= submit_tag "Search", name: nil, class: "btn btn-success" %>
 </p>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>IP</th>
      <th>ID</th>
      <th>Agent</th>
      <th>Browser</th>
      <th>OS</th>
      <th>Device</th>
      <th>Country</th>
      <th>City</th>
      <th>Region</th>
      <th>Time</th>
    </tr>
  </thead>

  <tbody>
    <% @recent_visits.each do |visit| %>
      <tr>
        <td><%= visit.ip  %></td>
        <td><%= visit.user_id %></td>
        <td><%= visit.user_agent %></td>
        <td><%= visit.browser %></td>
        <td><%= visit.os %></td>
        <td><%= visit.device_type %></td>
        <td><%= visit.country %></td>
        <td><%= visit.city %></td>
        <td><%= visit.region %></td>
        <td><%= visit.started_at.strftime("%B %e, %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>