config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'products#index'

  
  resources :reservations do
    member do
      put :cancel
    end
  end
  
  resources :products, only: [:index, :show] do
    collection do
      get 'c/:category_id', to: 'products#index', as: :categoried
    end
  end

  authenticate :user, lambda {|user| user.admin? } do
    get '/admin' => 'admin#index'
    get '/recent-reservations' => "pages#recent_reservations", path: '/admin/recent_reservations'
    get '/recent-visits' => "pages#recent_visits", path: '/admin/recent_visits'
    resources :broadcast_messages, only: [:create, :destroy], path: '/admin/broadcast_messages'


    mount PgHero::Engine, at: "pghero"
    mount RailsAdmin::Engine => '/admin/rails_admin', as: 'rails_admin'
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  available_at       :datetime
#  is_promoted        :boolean          default(FALSE)
#  user_id            :integer
#  description        :text
#  created_at         :datetime
#  updated_at         :datetime
#  employee           :string(255)
#  price              :string(255)
#  category_id        :integer
#  reservations_count :integer          default(0)
#  reservation_slots  :integer          default(1)
#  cover              :string(255)
#


class Product < ActiveRecord::Base
  mount_uploader :cover, CoverUploader

  has_paper_trail

  include PgSearch
  
  belongs_to :user
  belongs_to :category, counter_cache: true

  has_many :reservations
  
  pg_search_scope :search_by_name, :against => [:name, :price, :employee], :using => { :tsearch => { :prefix => true } }
  
  scope :promoted, -> { where(:is_promoted => true) }
  scope :not_promoted, -> { where(:is_promoted => false) }
  scope :recent, -> { order("available_at ASC") }
  scope :upcoming, lambda { where("available_at between ? and ?", Date.today.beginning_of_day, Date.today.end_of_day) }
  scope :reservation_quota, lambda { where("reservations_count < reservation_slots") }

  validates :name, presence: true
  validates :available_at, presence: true
  validates :description, presence: true
  validates :employee, presence: true
  validates :price, presence: true

  paginates_per 10


  def self.search_by_date(date)
    date = Date.parse(date)
    self.where("available_at > ? AND available_at < ?", date.beginning_of_day, date.end_of_day)
  end

  def time_available
    "#{available_at.strftime('%B %e, %H:%M')}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_product, only: [:show]

  def index
    @products = Product.includes(:category).recent.upcoming.reservation_quota
    @products = Product.search_by_date(params[:date]) unless params[:date].blank?

    if params[:category_id]
      @category = Category.where('lower(name) = ?', params[:category_id].downcase).first!
      @products = @products.where(category: @category)
    end
  end

  def show
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :available_at, :is_promoted, :user_id, 
        :category_id, :description, :employee, :price, :reservations_count, :reservation_slots)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.erb
<% @products.promoted.each do |product| %>
<% unless product.available_at < Time.now + (30.minutes) %>
   <div class="col-sm-4 col-lg-4 col-md-4">
     <div class="thumbnail">
       <span class="promo">
        <i class="fa fa-bullhorn has_top_tooltip" title="Promoted"></i>
        </span>
        <img src=<%= product.cover.thumb %>/>
          <div class="caption">
            <h4 class="pull-right"><%= product.price %> ден</h4>
              <h4><%= product.name %></h4>
              <p><%= product.description %></p>
          </div>
            <div class="clearfix">
              <div class="employees">
                <p class="pull-right"><%= link_to "Book Now!", new_reservation_path(product_id: product.name), class: "btn btn-primary btn-xs" %>
                <% if current_user.try(:admin?) %>
                  <%= link_to '<i class="fa fa-edit"></i>'.html_safe, rails_admin.edit_path(model_name: 'product', id: product.id), title: "Edit", class: "btn btn-danger btn-xs has_top_tooltip" %>
                  <% end %>
                </p>
                    <p><%= product.employee %> - <%= product.available_at.strftime('%H:%M') %>h</p>
                </div>
             </div>
      </div>
    </div>
<% end %>
<% end %>



<% @products.not_promoted.each do |product| %>
<% unless product.available_at < Time.now + (30.minutes) %>
   <div class="col-sm-4 col-lg-4 col-md-4">
     <div class="thumbnail">
     <img src=<%= product.cover.thumb %>/>
          <div class="caption">
            <h4 class="pull-right"><%= product.price %> ден</h4>
              <h4><%= product.name %> <small><%= product.available_at.strftime("%H:%M") %>h</small></h4>
              <p><%= product.description %></p>
          </div>
            <div class="clearfix">
              <div class="employees">
                <p class="pull-right"><%= link_to "Book Now!", new_reservation_path(product_id: product.name), class: "btn btn-primary btn-xs" %>
                <% if current_user.try(:admin?) %>
                  <%= link_to '<i class="fa fa-edit"></i>'.html_safe, rails_admin.edit_path(model_name: 'product', id: product.id), title: "Edit", class: "btn btn-danger btn-xs has_top_tooltip" %>
                  <% end %>
                </p>
                    <p><%= product.employee %> - <%= product.available_at.strftime('%H:%M') %></p>
                </div>
             </div>
      </div>
    </div>
<% end %>
<% end %>

app/views/products/_promoted.html.erb
<table class="table">

  <tbody>
    <% @products.promoted.each do |product| %>
    <% unless product.available_at < Time.now + (30.minutes) %>
      <tr class="warning">
        <td> <div class="label label-warning">PROMOTED</div> <%= product.name %></td>
        <td><%= product.employee %></td>
        <td><%= product.available_at.strftime("%B %e, %H:%M") %> </td>
        <td><%= product.price.to_i %> ден.</td>
        <td><%= product.description %></td>
        <td><%= link_to "Make a Reservation", new_reservation_path(product_id: product.name), class: "btn btn-primary btn-xs" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/products/index.html.erb
<div class="container">

<div class="row">
	<div class="panel panel-default">
	<div class="panel-body">
		<%= form_tag products_path, method: 'get', html: {role: "form"} do %>
  <p>
  <div class="col-md-6">
    <%= text_field_tag :date, params[:date], "data-behaviour" => "datepicker", id: "datepicker", placeholder: "Click here to find a product by date", class: "form-control" %>
  </div>
    <%= submit_tag "Search", name: nil, class: "btn btn-success" %>
 </p>
<% end %>
</div>
	</div>

<div class="row">

<div class="col-md-3">
	<ul class="nav nav-pills nav-stacked">
		<li class=<%= 'active' unless @category.present? %>><%= link_to "All Products", products_path, class: "list-group-item" %></li>
		<% Category.order(products_count: :desc).each do |category| %>
		<li class=<%= 'active' if category == @category %>><%= link_to "#{category.name}", categoried_products_path(category_id: category.name), class: "list-group-item" %></li>
		<% end %>
	</ul>
</div>

<div class="col-md-9">

<% if @products.any? %>

<%= render 'products/products' %>

<% else %>

<div class="text-muted"><p class="text-center">There are no services available at this time :(</p></div>

<% end %>

</div>
</div>



</div>

</div>