config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'products#index'

  
  resources :reservations do
    member do
      put :cancel
    end
  end
  
  resources :products, only: [:index, :show] do
    collection do
      get 'c/:category_id', to: 'products#index', as: :categoried
    end
  end

  authenticate :user, lambda {|user| user.admin? } do
    get '/admin' => 'admin#index'
    get '/recent-reservations' => "pages#recent_reservations", path: '/admin/recent_reservations'
    get '/recent-visits' => "pages#recent_visits", path: '/admin/recent_visits'
    resources :broadcast_messages, only: [:create, :destroy], path: '/admin/broadcast_messages'


    mount PgHero::Engine, at: "pghero"
    mount RailsAdmin::Engine => '/admin/rails_admin', as: 'rails_admin'
  end

end

app/views/layouts/_broadcast.html.erb
<% if broadcast_message.present? %>
<div class="broadcast-message">
	<i class="fa fa-bullhorn"></i> <%=h broadcast_message.message %>
</div>
<% end %>

app/views/layouts/_nav_panel.html.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Kozmeticar</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      <li class=<%= 'active' if request.original_fullpath =~ /^\/products/ %>><%= link_to "Services", products_path %></li>
      <% if user_signed_in? %>
      <li class=<%= 'active' if request.original_fullpath =~ /^\/reservations/ %>><%= link_to "Your Reservations", reservations_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li class=<%= 'active' if request.original_fullpath =~ /^\/users/ %>><%= link_to "#{current_user.fullname}", edit_user_registration_path, title: "Settings", class: "has_bottom_tooltip" %></li>
      <% if current_user.try(:admin?) %>
      <li class=<%= 'active' if request.original_fullpath =~ /^\/admin/ %>><%= link_to "Admin", admin_path %></li>
      <% end %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
      <li class=<%= 'active' if request.original_fullpath =~ /^\/login/ %>><%= link_to "Login", new_user_session_path %> </li>
      <li class=<%= 'active' if request.original_fullpath =~ /^\/register/ %>><%= link_to "Register", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kozmeticar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'peek/bar' %>

  <%= render 'layouts/broadcast' %>

	<%= render 'layouts/nav_panel' %>

<div class="container">
       <%= render 'shared/messages' %>
       <%= yield %>
</div>

</body>
</html>